name: RGHAFS20
channels:     
  - local                                                                                                                                           
  - conda-forge                                                                                                                                          
  - defaults
dependencies:
  - ipython
  - jupyter
  - path.py
  - python=3.6
  - r-base=3.6 
  - rpy2=2.9.4
  - rghafs20
