name: RGHAFS20
channels:     
  - local                                                                                                                                           
  - conda-forge                                                                                                                                          
  - defaults
dependencies:
  - jupyter
  - path.py
  - r-base 
  - rpy2
  - rghafs20
